### ISSUE TITLE
Simplify neighbourhood notation

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#102]
Let's simplify this definition:

<img width="429" alt="screen shot 2016-10-26 at 18 37 44" src="https://cloud.githubusercontent.com/assets/544572/19735307/53255cba-9bab-11e6-80ef-e3cd60220065.png">

Maybe like this:

```
$N^{+}(A) = \{((A, v) \in \mathcal{E})\}$
```

Similarly below.

**Comment by OrfeasLitos** [comment]
The neighbourhood is a set of nodes, so with this approach it should be

`N^{+}(A)_j = \{v \in V_j : (A, v) \in E_j\}`,

which isn't really simpler. Also the way it is now shows our intention when defining the neighbourhood. We don't really care if there is an edge or something, we concentrate on the existence of direct trust. What's more, dropping the subscript may be confusing because we use it throughout the paper.
