### ISSUE TITLE
Remove neighborhood definition

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#122]
We are defining neighbourhoods but not flows. What kind of readers knows the one without the other? Lets remove the formal definitions from the end and maybe find a reference for this notation somewhere?

**Comment by OrfeasLitos** [comment]
The use we make with flows could be a paper in itself (Flow decomposition, proof that outgoing flow from source is equal to incoming flow to sink, etc). We are actually defining flows in the main body and neighbourhoods only in the appendix, which makes clear that we assume the reader is more familiar with neighbourhoods than with flows. Also, the notation we use for neighbourhoods is not standard, since we use the turn subscript and furthermore do not define the neighbourhood based on the existing edges, but on the existence of a 1-of-2 multisig. I don't think that it will be helpful for any reader to remove the neighbourhood definition. The ones that already know it can just skip it and the rest will understand what we are talking about.
