### ISSUE TITLE
Numbering every equation?

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#128]
I know the FC style automatically numbers every equation. However, this seems like a lot of overkill. It reduces readability and takes up (horizontal) space without adding value. While for a book it would be useful, for a paper it seems like too much. What do you think?

**Comment by OrfeasLitos** [comment]
I agree. We should keep numbers only in important and referenced equations.

**Comment by OrfeasLitos** [comment]
For example,

![equations](https://cloud.githubusercontent.com/assets/18602747/19829247/a69f8418-9dd3-11e6-9225-3f701bb008ab.png)

Here equations 1, 2 will lose the numbers because they don't describe something that is always true (possibly y_B doesn't even exist), but 3 and 4 will keep the numbers, because they are important conditions for a turn to hold.

**Comment by OrfeasLitos** [comment]
Also lemma/theorem results do not need numbers, since we refer to them through the lemma/theorem name.
