### ISSUE TITLE
Assets, capital definition

### ISSUE THREAD

**Issue by dimkarakostas** [OrfeasLitos/TrustIsRisk#131]
It is not very clear that assets remain static after the initialization. Perhaps move Definition 16 out of the Appendix.

**Comment by OrfeasLitos** [comment]
They don't remain static, they can be reduced if somebody A trusts steals from her. If there is room, the assets will be defined right after the capital, along with an explanation that A's outgoing trust is considered to be A's money.

**Comment by dimkarakostas** [comment]
The assets cannot be topped up in a later stage, so each player can spend only its initial capital in trusting other players. This is not clearly described intuitively.

**Comment by OrfeasLitos** [comment]
They can be topped up, since the  capital is defined as the total money a player has in p2pkh, which can be modified at any time.

**Comment by OrfeasLitos** [comment]
Also the fact that both the capital and the assets can be modified from turn to turn can be seen because they both have turn j as a subscript.

**Comment by dionyziz** [comment]
There is no game action that allows a player to top-up.

**Comment by OrfeasLitos** [comment]
Similarly it remains unexplained how the initial Cap is set. The definition jumps directly to a dynamic setting condition...

**Comment by OrfeasLitos** [comment]
So we have an apparent problem with two possible solutions. The problem is that, as defined and used now, the capital contains a contradiction: The definition _implies_ that TrustIsRisk Game should be aware real-time about the state of the utxo, but this is not the case in the implementation of the algorithm and is against the spirit of the paper, because it introduces under the table a dynamic component. Also it is an outright contradiction that the capital is _statically_ updated by TrustIsRisk Game and Transitive Game.

There are two possible courses of action: Either remove all updates to the capital in the algorithms, essentially removing the need of capital throughout the paper, or change the definition so as not to connect it with the utxo. In the latter case, we could informally state the true nature we would like capital to have after the expansion to the dynamic setting. A simple way is to substitute the current informal explanation with the formal definition and vice versa.

Which choice do you prefer? I think that the simplest and cleanest solution is the second one.

**Comment by dionyziz** [comment]
Just say that the capital is the initial UTXO before the game begins.

**Comment by OrfeasLitos** [comment]
Hmm this is too restrictive. Why not add a TopUp(x) action in the Turn definition? And add informally that the player has to have x bitcoins in the utxo. Of course the validate/commit turn must be updated accordingly

**Comment by OrfeasLitos** [comment]
The action will be named ModCap(x), because the player may as well reduce her capital.

**Comment by OrfeasLitos** [comment]
We finally decided to scratch the modcap(x) and just say that cap_0 is defined to be the initial funds of each player in the utxo.

**Comment by OrfeasLitos** [comment]
It will be added again when the dynamic model is built.

**Comment by OrfeasLitos** [comment]
I leave this open to check the capital definition rephrasing
