### ISSUE TITLE
appendix numbering

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#144]
The numbers in the appendix are a single digit, as per lncs, and they start from 1. Is this the correct way or should we continue the numbering from the previous sections, that is start from 9 (blergh)?

**Comment by dionyziz** [comment]
Looks fine. The one thing I don't like in the appendix typesetting is that our proofs look like this:

```
Proof (MaxFlows Are Transitive Games Lemma (1)).
blah blah QED
```

It is ugly. Perhaps we can change it to something like this:

```
Lemma 1 (MaxFlows Are Transitive Games).
Proof.
blah blah QED
```

i.e. name the theorem properly, just don't repeat its statement. I'm not sure these can be references though. Otherwise something like this may be OK:

```
MaxFlows Are Transitive Games Lemma (1)
Proof.
blah blah QED
```

**Comment by OrfeasLitos** [comment]
Did something similar
