### ISSUE TITLE
Correct references from lemma (1) and lemma (2) to lemma~1 and lemma~2 (FC027)

### ISSUE THREAD

**Issue by OrfeasLitos** [OrfeasLitos/TrustIsRisk#183]

**Comment by OrfeasLitos** [comment]
Solved with commit 2e2f455.

**Comment by dionyziz** [comment]
You can use "Fix #183" in your commit message to associate it with a github
issue.

On Jan 25, 2017 14:51, "Orfeas Stefanos Thyfronitis Litos" <
notifications@github.com> wrote:

Solved with commit 2e2f455
<https://github.com/OrfeasLitos/TrustIsRisk/commit/2e2f4556bdf9c0fbb78de4a75e40e430f08383d7>
.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/OrfeasLitos/TrustIsRisk/issues/183#issuecomment-275100349>,
or mute the thread
