### ISSUE TITLE
Describe conservative strategy from an economic point of view

### ISSUE THREAD

**Issue by dionyziz** [OrfeasLitos/TrustIsRisk#9]

**Comment by OrfeasLitos** [comment]
Rationale:

__The rationale behind this strategy arises from a real-world common situation. Suppose a client, an intermediary and a producer. The client entrusts some value to the intermediary so that the latter can buy the desired product from the producer and deliver it to the client. The intermediary in turn entrusts an equal value to the producer, who needs the value up front to be able to complete the production process. However the producer eventually does not give the product neither reimburses the value, due to bankruptcy or decision to exit the market with a benefit. The intermediary can choose either to reimburse the client and suffer the loss, or refuse to return the money and lose the client's trust. The latter choice for the intermediary is exactly the conservative strategy. It is used throughout this work as a strategy for all the intermediary players because it models effectively the worst-case scenario that a client can face after an evil player decides to steal everything she can and the rest of the players do not engage in evil activity.__
